import { Inter } from "next/font/google";
import "./globals.css";
import AppSidebar from "@/components/AppSidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import React from "react";
import { Button } from "@/components/ui/button";
import { SendIcon } from "lucide-react";
import { Dialog } from "@radix-ui/react-dialog";
import {
  DialogClose,
  DialogContent,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import courierNames from "@/constants/courierNames";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import SendSMSForm from "@/features/home/components/SendSMSForm";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  subsets: [
    "latin",
    "latin-ext",
    "cyrillic",
    "cyrillic-ext",
    "greek",
    "greek-ext",
  ],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Pushtidhara Database",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased flex gap-6 min-h-dvh`}>
        <SidebarProvider>
          <AppSidebar />
          <main className="bg-gray-50 text-gray-800 flex flex-col w-full">
            <header className="flex justify-between gap-6 bg-gray-800 px-4 py-2">
              <div className="flex items-center gap-2">
                <SidebarTrigger className="flex items-center justify-center text-white md:hidden" />
                <h3 className="text-2xl font-bold text-blue-600">
                  <a href="/">Pushtidhara DB</a>
                </h3>
              </div>
              <div>
                <Dialog>
                  <DialogTrigger asChild>
                    <Button
                      variant="outline"
                      className="bg-gray-800 text-gray-200 border-gray-600 hover:text-gray-200/80 hover:bg-gray-800"
                    >
                      <SendIcon />
                      Send SMS
                    </Button>
                  </DialogTrigger>
                  <DialogContent>
                    <DialogTitle>Send SMS</DialogTitle>
                    <Tabs
                      defaultValue="orderConfirmation"
                      className="w-full flex flex-col gap-5"
                    >
                      <TabsList>
                        <TabsTrigger value="orderConfirmation">
                          Order Confirmation
                        </TabsTrigger>
                        <TabsTrigger value="trackingParcel">
                          Tracking Parcel
                        </TabsTrigger>
                      </TabsList>
                      <TabsContent value="orderConfirmation">
                        <SendSMSForm />
                      </TabsContent>
                      <TabsContent value="trackingParcel">
                        Parcel Tracking Message Sending Component Here
                      </TabsContent>
                    </Tabs>
                  </DialogContent>
                </Dialog>
              </div>
            </header>
            <main className="p-6 grow">{children}</main>
          </main>
        </SidebarProvider>
        <Toaster />
      </body>
    </html>
  );
}
