import { Inter } from "next/font/google";
import "./globals.css";
import AppSidebar from "@/components/AppSidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Button } from "@/components/ui/button";
import { SendIcon } from "lucide-react";
import { Dialog } from "@radix-ui/react-dialog";
import {
  DialogContent,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import SendSMSForm from "@/features/home/components/SendSMSForm";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  subsets: [
    "latin",
    "latin-ext",
    "cyrillic",
    "cyrillic-ext",
    "greek",
    "greek-ext",
  ],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Pushtidhara Database",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased min-h-dvh`}>
        <SidebarProvider className="flex flex-col">
          <header className="bg-gray-900 px-8 py-2 sticky top-0 z-50 w-full flex justify-between">
            <div className="flex items-center gap-2">
              <SidebarTrigger className="flex items-center justify-center text-white" />
              <h3 className="text-2xl font-bold text-blue-400">
                <a href="/">Pushtidhara DB</a>
              </h3>
            </div>
            <div>
              <Dialog>
                <DialogTrigger asChild>
                  <Button
                    variant="outline"
                    className="bg-gray-800 text-gray-200 border-gray-600 hover:text-gray-200/80 hover:bg-gray-800"
                  >
                    <SendIcon />
                    Send SMS
                  </Button>
                </DialogTrigger>
                <DialogContent>
                  <DialogTitle>Send SMS</DialogTitle>
                  <SendSMSForm />
                </DialogContent>
              </Dialog>
            </div>
          </header>
          <main className="flex grow">
            <AppSidebar />
            <main className="bg-gray-50 text-gray-800 p-6 grow">
              {children}
            </main>
          </main>
          <Toaster richColors />
        </SidebarProvider>
      </body>
    </html>
  );
}
